version: "3"
services:
    mariadb:
        container_name: "comic-api-mariadb"
        image: mariadb:10.7
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - db_conf:/etc/mysql
volumes:
    db_data:
    db_conf:

