# This is a basic workflow to help you get started with Actions

name: Maven Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.bump.outputs.version }}

    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v2

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-email: 69063372+kevinpita@users.noreply.github.com
          git-username: Kevin Pita

      - name: Docker build
        run: |
          docker build . -t kevinpita/comicstoreapi:${{ steps.bump.outputs.version }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: |
          docker push kevinpita/comicstoreapi:${{ steps.bump.outputs.version }}

